name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linter:
    name: Lint code base
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: Fetch GO dependencies
      #   run: go mod vendor
      #   working-directory: wasm
      - name: Lint code base
        uses: github/super-linter@v3.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOS: js
          GOARCH: wasm

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup GO
        uses: actions/setup-go@v2
      - name: Make
        run: make
