name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  super-linter:
    name: Lint code base
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint code base
        uses: github/super-linter@v4.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # TODO: Fix golangci-lint setup
          VALIDATE_GO: false

  golangci:
    name: GO lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: wasm
          args: --timeout 5m
        env:
          GOOS: js
          GOARCH: wasm

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup GO
        uses: actions/setup-go@v2
      - name: Make
        run: make
