name: Publish to GitHub pages

on:
  push:
    branches:
      - master

permissions: read-all

jobs:
  publish:
    name: Publish to GitHub pages
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v4
      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Make
        run: |
          mkdir gh-pages
          make GZIP_OPT="--best" DIR=gh-pages publish
      - name: Publish to GitHub pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
