name: Publish to GitHub pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish to GitHub pages
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v3
      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - name: Make
        run: |
          mkdir gh-pages
          make GZIP_OPT="--best" DIR=gh-pages publish
      - name: Publish to GitHub pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
